name: Publish to PyPI
on: 
  push:
    tags:
      - v**

jobs:
  publish:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install poetry
        id: poetry
        run: pipx install poetry~=1.3.1
      - name: Install poetry-dynamic-versioning
        id: poetry-dynamic-versioning
        run: poetry self add "poetry-dynamic-versioning[plugin]"
      - name: Setup python
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: "3.7"
          cache: 'poetry'
      - name: Install project
        id: install
        run: poetry install
      - name: mypy
        id: mypy
        run: poetry run mypy .
      - name: black
        id: black
        run: poetry run black --check .
      - name: build
        id: build
        run: poetry build
      - name: test
        id: test
        run: poetry run pytest --cov=splitlog tests/
      - name: Publish
        id: publish
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
        uses: pypa/gh-action-pypi-publish@v1.8.5
        with:
          user: ${{ secrets.PYPI_USER_NAME }}
          password: ${{ secrets.PYPI_PASSWORD }}
          repository_url: ${{ secrets.PYPI_REPO_URL }}
