name: Release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build sdist
        run: pipx run build --sdist

      - uses: actions/upload-artifact@v3
        with:
          path: dist/*.tar.gz

  upload_testpypi:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    needs: [build_sdist]
    runs-on: ubuntu-latest
    environment:
      name: testpypi
      url: https://test.pypi.org/p/splitlog
    permissions:
      id-token: write
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - uses: actions/download-artifact@v3
        with:
          name: artifact
          path: dist

      - name: Publish distribution 📦 to Test PyPI
        uses: pypa/gh-action-pypi-publish@v1.8.6
        with:
          repository-url: https://test.pypi.org/legacy/

  upload_pypi:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    needs: [build_sdist, upload_testpypi]
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/splitlog
    permissions:
      id-token: write
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - uses: actions/download-artifact@v3
        with:
          name: artifact
          path: dist

      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@v1.8.6

