name: Release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build sdist
        run: pipx run build

      - uses: actions/upload-artifact@v4
        with:
          path: dist/*

  upload_testpypi:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    needs: [build]
    runs-on: ubuntu-latest
    environment:
      name: testpypi
      url: https://test.pypi.org/p/splitlog
    permissions:
      id-token: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: artifact
          path: dist

      - name: Publish distribution 📦 to Test PyPI
        uses: pypa/gh-action-pypi-publish@v1.10.3
        with:
          attestations: true
          repository-url: https://test.pypi.org/legacy/

  upload_pypi:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    needs: [build, upload_testpypi]
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/splitlog
    permissions:
      id-token: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: artifact
          path: dist

      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@v1.10.3
        with:
          attestations: true
